# Arquivo de configuração do GitLab CI para Automação Cypress

stages:
  - test

# Cache para node_modules e binários do Cypress para acelerar as próximas execuções
cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - cache/Cypress/
    - node_modules/

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cypress-tests:
  stage: test
  # Utilizando a imagem oficial do Cypress compatível com a sua versão do package.json (15.9.0)
  image: cypress/included:15.9.0
  script:
    # Instala as dependências do projeto de forma limpa e otimizada para CI
    - npm ci
    # Verifica se o Cypress está corretamente instalado e pronto para rodar
    - npx cypress verify
    # Executa o script de teste especificado no seu package.json
    - npm run teste:sauce
  artifacts:
    name: "cypress-test-results-$CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
      - cypress/reports/
    expire_in: 1 week
