describe('login',()=>{
    beforeEach(()=>{
       cy.visit_login()
    })
    it('deve realizar o login', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.url_inicial()
    })
    it('login inválido', ()=>{
        cy.login('standard','secret_sauce')
        cy.modal_erro().should('contain','password do not match any user')
    })
    it('Realizar o logout', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.botao_hamburguer()
        cy.link_logout()
    })
    it('Adicionar backpack no carrinho', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.add_packpack()
    })
    it('Visualizar o carrinho', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.add_packpack() 
        cy.carrinho_de_compras()
    })
    it('botao comprar', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.add_packpack() 
        cy.carrinho_de_compras()
        cy.botao_comprar()
    })
    it('informacoes pessoais', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.add_packpack() 
        cy.carrinho_de_compras()
        cy.botao_comprar()
        cy.dados('Thiago','Carli','18086763')
    })
    it('botao continuar', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.add_packpack() 
        cy.carrinho_de_compras()
        cy.botao_comprar()
        cy.dados('Thiago','Carli','18086763')
        cy.botao_continuar()
    })
    it('botao finalizar', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.add_packpack() 
        cy.carrinho_de_compras()
        cy.botao_comprar()
        cy.dados('Thiago','Carli','18086763')
        cy.botao_continuar()
        cy.botao_finalizar()
    })
    it('botao voltar para a tela inicial', ()=>{
        cy.login('standard_user','secret_sauce')
        cy.add_packpack() 
        cy.carrinho_de_compras()
        cy.botao_comprar()
        cy.dados('Thiago','Carli','18086763')
        cy.botao_continuar()
        cy.botao_finalizar()
        cy.botao_voltar_para_a_tela_inicial()
    })
})