describe ('Register Parabank', () => {
    beforeEach(() => {
        cy.url_parabank()
    })
        it('Registro Com Sucesso', () => {      
            cy.get('#loginPanel > :nth-child(3) > a').click()
            cy.get('[name="customer.firstName"]').type('Thiago')
            cy.get('[name="customer.lastName"]').type('Gois')
            cy.get('[name="customer.address.street"]').type('Rua Teste')
            cy.get('[name="customer.address.city"]').type('Sorocaba')
            cy.get('[name="customer.address.state"]').type('Sao Paulo')
            cy.get('[name="customer.address.zipCode"]').type('111111111')
            cy.get('[name="customer.phoneNumber"]').type('11999999999')
            cy.get('[name="customer.ssn"]').type('0000')
            cy.get('[name="customer.username"]').type('tgois')
            cy.get('[name="customer.password"]').type('teste1')
            cy.get('[name="repeatedPassword"]').type('teste1')
            cy.get('[colspan="2"] > .button').click()
            cy.get('#rightPanel').should('contain', 'Your account was created successfully. You are now logged in.')
        })

        it('Registro Com campo vazio', () => {      
            cy.get('#loginPanel > :nth-child(3) > a').click()
            cy.get('[name="customer.firstName"]').type('Thiago')
            cy.get('[name="customer.address.street"]').type('Rua Teste')
            cy.get('[name="customer.address.city"]').type('Sorocaba')
            cy.get('[name="customer.address.state"]').type('Sao Paulo')
            cy.get('[name="customer.ssn"]').type('0000')
            cy.get('[name="customer.username"]').type('tgois')
            cy.get('[name="customer.password"]').type('teste1')
            cy.get('[name="repeatedPassword"]').type('teste1')
            cy.get('[colspan="2"] > .button').click()
            cy.get(':nth-child(2) > [width="50%"]').should('contain', 'Last name is required.')
            //  cy.contains('Last name is required.')
            cy.get(':nth-child(6) > [width="50%"]').should('contain', 'Zip Code is required.')
            //  cy.contains('Zip Code is required. ')
        })

        it.only('Registro com usuário existente', () => {
           cy.get('#loginPanel > :nth-child(3) > a').click()
           cy.get('[name="customer.firstName"]').type('Thiago')
           cy.get('[name="customer.lastName"]').type('Gois')
           cy.get('[name="customer.address.street"]').type('Rua Teste')
           cy.get('[name="customer.address.city"]').type('Sorocaba')
           cy.get('[name="customer.address.state"]').type('Sao Paulo')
           cy.get('[name="customer.address.zipCode"]').type('111111111')
           cy.get('[name="customer.phoneNumber"]').type('11999999999')
           cy.get('[name="customer.ssn"]').type('0000')
           cy.get('[name="customer.username"]').type('tgois')
           cy.get('[name="customer.password"]').type('teste1')
           cy.get('[name="repeatedPassword"]').type('teste1')
           cy.get('[colspan="2"] > .button').click()
           cy.get(':nth-child(10) > [width="50%"]').should('contain', 'This username already exists.')    
            
   })    

})      